import fs from 'node:fs';
const fail=[];
const read=p=>fs.readFileSync(p,'utf8');
const admin=read('public/admin-account.js');
const home=read('public/index.html');
const worker=read('src/worker.js');
const wrangler=read('wrangler.jsonc');

if(fs.existsSync('public/admin/index.html'))fail.push('A rota pública /admin ainda existe.');
if(!home.includes('id="ccAdminNav"'))fail.push('Minha Conta sem botão administrativo oculto.');
if(!home.includes('src="/admin-account.js"'))fail.push('Minha Conta não carrega o módulo administrativo.');
if(!home.includes("if(t==='admin')"))fail.push('Aba administrativa não está integrada ao clientTab.');
if(!admin.includes('/api/admin/status'))fail.push('Módulo admin sem consulta de elegibilidade.');
if(!admin.includes('/api/admin/setup'))fail.push('Módulo admin sem criação segura de senha.');
if(!admin.includes('/api/admin/login'))fail.push('Módulo admin sem login separado.');
if(!admin.includes('/api/admin/dashboard'))fail.push('Módulo admin sem dashboard protegido.');
if(!admin.includes('data-v="alerts"'))fail.push('Painel sem aba ALERTAS.');
if(!admin.includes('data-v="finance"'))fail.push('Painel sem aba FINANCEIRO.');
if(!admin.includes('data-v="shipping"'))fail.push('Painel sem aba ENVIOS.');
if(!admin.includes('data-v="products"'))fail.push('Painel sem aba PRODUTOS.');
if(!admin.includes('data-v="promotions"'))fail.push('Painel sem aba PROMOÇÕES.');
if(!admin.includes('data-v="system"'))fail.push('Painel sem aba SISTEMA.');
if(!admin.includes("if(adminView==='system')"))fail.push('Aba SISTEMA sem renderização.');
if(!admin.includes('Saúde da configuração'))fail.push('Sistema sem quadro de saúde.');
if(!admin.includes('Histórico administrativo'))fail.push('Sistema sem trilha de auditoria.');
if(!worker.includes('CREATE TABLE IF NOT EXISTS admin_audit_log'))fail.push('Worker sem tabela de auditoria.');
if(!worker.includes('async function recordAdminAudit'))fail.push('Worker sem gravador de auditoria.');
if(!worker.includes('"test_orders_deleted"')||!worker.includes('"promotion_save"')||!worker.includes('"promotion_toggle"')||!worker.includes('"notifications_read"'))fail.push('Auditoria não cobre ações administrativas essenciais.');
if(!worker.includes('mercadoPagoMode:mp.testMode?"TESTE":"PRODUÇÃO"'))fail.push('Sistema não informa modo do Mercado Pago.');
if(!worker.includes('canonicalHost:"www.valenzaparfums.com.br"'))fail.push('Sistema não confirma domínio canônico.');
if(!worker.includes('env.DB.prepare(realOrdersCte+"SELECT oi.product_id'))fail.push('Mais vendidos ainda pode incluir pedidos de teste.');
if(!worker.includes('pending_real'))fail.push('Dashboard sem contador de pagamentos pendentes reais.');
if(!worker.includes('pendingOrders:Number(fin.pending_real||0)'))fail.push('Resumo ainda usa pendências de teste.');
if(!admin.includes("['EnvioEcom',!!s.envioEcom&&!!s.envioOriginCep"))fail.push('Sistema marca EnvioEcom como OK sem validar CEP de origem.');
if(!admin.includes('não exibe tokens, senhas ou chaves'))fail.push('Sistema não deixa claro que segredos não são exibidos.');
if(!admin.includes("if(adminView==='promotions')"))fail.push('Aba PROMOÇÕES sem renderização.');
if(!admin.includes('/api/admin/promotions/save')||!admin.includes('/api/admin/promotions/toggle'))fail.push('Aba PROMOÇÕES sem ações administrativas.');
if(!worker.includes('CREATE TABLE IF NOT EXISTS admin_promotions'))fail.push('Worker sem tabela de campanhas.');
if(!worker.includes('/api/promotions/active'))fail.push('Worker sem endpoint público da campanha ativa.');
if(!worker.includes('currentAdmin(request,env)'))fail.push('Rotas administrativas não estão protegidas.');
if(!home.includes('id="valenzaPromoBar"'))fail.push('Loja sem faixa promocional pública.');
if(!home.includes("fetch('/api/promotions/active?t='"))fail.push('Faixa promocional não consulta campanha ativa.');
if(!home.includes("el.textContent=["))fail.push('Faixa promocional deve usar textContent.');
if(admin.includes('ALTERAR PREÇO AUTOMATICAMENTE'))fail.push('Promoções não deve alterar preço automaticamente.');
if(!admin.includes("if(adminView==='products')"))fail.push('Aba PRODUTOS sem renderização.');
if(!admin.includes('Math.floor((cents*95+50)/100)/100'))fail.push('Aba PRODUTOS não replica a fórmula PIX do servidor.');
if(!admin.includes('vaProductSearch'))fail.push('Aba PRODUTOS sem busca.');
if(!admin.includes('ESTOQUE BAIXO')||!admin.includes('ESGOTADOS'))fail.push('Aba PRODUTOS sem estados de estoque.');
if(!admin.includes("if(adminView==='shipping')"))fail.push('Aba ENVIOS sem renderização.');
if(!admin.includes('Esta tela não cria nem altera postagens'))fail.push('Aba ENVIOS não declara modo somente leitura.');
if(!admin.includes('vaCopyTrack'))fail.push('Aba ENVIOS sem ação de copiar rastreio.');
if(!worker.includes('shippingSummary')||!worker.includes('shippingRows'))fail.push('Dashboard sem agregação operacional de envios.');
if(!worker.includes('labelReady:Number(sh.label_ready||0)'))fail.push('Envios sem contador de etiqueta pronta.');
if(!worker.includes('!x.is_test_account&&String(x.status)==="Pago"'))fail.push('Alerta de envio ainda considera pedidos da conta de teste.');
if(!admin.includes("if(adminView==='finance')"))fail.push('Aba FINANCEIRO sem renderização.');
if(!admin.includes('Faturamento real')||!admin.includes('Pagos reais'))fail.push('Resumo não separa vendas reais de testes.');
if(!worker.includes('const realOrdersCte='))fail.push('Worker sem separação de pedidos reais no Financeiro.');
if(!worker.includes('testPaidIgnored'))fail.push('Financeiro não contabiliza testes ignorados.');
if(!worker.includes('pix_revenue_30d')||!worker.includes('card_revenue_30d'))fail.push('Financeiro sem divisão PIX/cartão.');
if(!worker.includes('freight_30d'))fail.push('Financeiro sem total de frete dos últimos 30 dias.');
if(!admin.includes('Central de alertas'))fail.push('Aba ALERTAS sem conteúdo.');
if(!admin.includes('/api/admin/notifications/read'))fail.push('Painel sem ação de marcar alertas como lidos.');
if(!worker.includes('CREATE TABLE IF NOT EXISTS admin_notifications'))fail.push('Worker sem tabela de notificações administrativas.');
if(!worker.includes('async function notifyPaidOrder(env,orderId)'))fail.push('Worker sem gerador de alerta de compra paga.');
if(!worker.includes('webhookMercadoPago(request,env,ctx)')||!worker.includes('const task=notifyPaidOrder(env,pid)'))fail.push('Webhook do Mercado Pago não dispara alerta de venda.');
if(!worker.includes('retryPendingSaleNotifications(env)'))fail.push('Cron não tenta reenviar avisos de venda que falharam.');
if(!worker.includes('if(Number(ins.meta?.changes||0)<1)return;'))fail.push('Aviso de venda não usa a inserção única como trava contra e-mail duplicado.');
if(!worker.includes('orderBelongsToAdmin(env,row)'))fail.push('Aviso de venda não exclui completamente pedidos da conta administrativa.');
if(!worker.includes('productSales:productSales.results||[]'))fail.push('Produtos não recebe vendas completas de todos os itens.');
if(!admin.includes('(d.productSales||[])'))fail.push('Aba Produtos ainda usa apenas o top 10 para VENDIDOS.');
if(!worker.includes('local_delivery')||!admin.includes('ENTREGA LOCAL'))fail.push('Envios não distingue entrega local de postagem EnvioEcom.');
if(!worker.includes('const paidWithoutShipping=Number(sh.awaiting||0)'))fail.push('Alerta de envio não usa o total completo de pedidos aguardando postagem.');
if(!admin.includes('const localIso=id=>')||!admin.includes('z.toISOString()'))fail.push('Promoções não converte datetime-local pelo fuso do navegador.');
if(!worker.includes('Nova venda confirmada | VALENZA PARFUMS'))fail.push('Worker sem aviso de venda por e-mail.');
if(!worker.includes('SELECT 1 ok FROM admin_credentials WHERE customer_id=?'))fail.push('Alerta de compra não exclui a conta administrativa/testes.');
if(!worker.includes('/api/admin/notifications/read'))fail.push('Worker sem endpoint protegido de leitura dos alertas.');
if(!worker.includes('unreadNotifications'))fail.push('Dashboard não entrega contador de alertas não lidos.');
if(!admin.includes("if(adminView==='analytics')"))fail.push('Aba Analytics ainda não possui renderização real.');
if(!admin.includes('Localização das visitas'))fail.push('Analytics sem painel de localização.');
if(!admin.includes('Origem do tráfego'))fail.push('Analytics sem painel de origem do tráfego.');
if(!admin.includes('Funil · últimos 30 dias'))fail.push('Analytics sem funil de conversão.');
if(!worker.includes('async function analyticsDashboard(env)'))fail.push('Worker sem agregador Analytics administrativo.');
if(!worker.includes('analytics=await analyticsDashboard(env)'))fail.push('Dashboard não entrega métricas Analytics.');
if(!admin.includes("credentials:'same-origin'"))fail.push('Módulo admin não usa sessão same-origin.');
for(const route of ['status','setup','login','logout','dashboard']){
 if(!worker.includes('/api/admin/'+route))fail.push('Rota /api/admin/'+route+' ausente.');
}
if(!worker.includes('admin_credentials'))fail.push('Credenciais administrativas não possuem tabela dedicada.');
if(!worker.includes('admin_sessions'))fail.push('Sessões administrativas não possuem tabela dedicada.');
if(!worker.includes('admin_login_attempts'))fail.push('Proteção contra tentativas repetidas ausente.');
if(!worker.includes('valenza_admin='))fail.push('Cookie administrativo separado ausente.');
if(!worker.includes('SameSite=Strict'))fail.push('Cookie administrativo sem SameSite=Strict.');
if(!worker.includes('HttpOnly; Secure'))fail.push('Cookie administrativo sem HttpOnly/Secure.');
if(!worker.includes('__Host-valenza_session='))fail.push('Sessão do cliente não usa cookie único __Host- seguro.');
if(!worker.includes('legacySessionClearCookies'))fail.push('Migração não limpa cookies antigos aurea_session.');
if(worker.includes('sessionCookies(request,token)'))fail.push('Sessão do cliente voltou a gravar cookies duplicados.');
if(!worker.includes('if(url.protocol!=="https:")'))fail.push('Worker não força HTTP para HTTPS antes da autenticação.');
if(!worker.includes('target.protocol="https:"'))fail.push('Redirecionamento canônico não força HTTPS.');
if(!worker.includes('Strict-Transport-Security'))fail.push('Worker não envia HSTS para manter a loja em HTTPS.');
if(!home.includes("credentials:'include'"))fail.push('Fluxo de conta não envia credenciais explicitamente.');
if(!worker.includes('Seu cadastro pendente expirou após 24 horas'))fail.push('Reenvio não informa corretamente cadastro expirado.');
if(!home.includes("if(d.expired||d.notPending)"))fail.push('Front não direciona cadastro expirado para CRIAR CONTA.');
if(!worker.includes('allowedAdminEmail'))fail.push('Conta administrativa não está vinculada à conta autorizada.');
if(!worker.includes('if(url.pathname==="/admin"||url.pathname.startsWith("/admin/"))'))fail.push('/admin não foi bloqueado com 404.');
if(!wrangler.includes('"ADMIN_EMAILS"'))fail.push('ADMIN_EMAILS não configurado.');
if(!wrangler.includes('"ADMIN_USERNAME": "wesleymartins"'))fail.push('Usuário administrativo esperado não configurado.');
if(!wrangler.includes('"/admin"')||!wrangler.includes('"/admin/*"'))fail.push('run_worker_first não intercepta /admin e /admin/* antes do fallback SPA.');
if(/ADMIN_PASSWORD/i.test(home+admin+worker+wrangler))fail.push('Senha administrativa não deve ficar em código ou variável pública.');
if(!worker.includes('/api/admin/orders/delete-tests'))fail.push('Rota de limpeza dos pedidos de teste ausente.');
if(!worker.includes('admin_deleted_test_orders'))fail.push('Exclusão de testes sem arquivo interno de segurança.');
if(!worker.includes('Venda de cliente protegida'))fail.push('Trava para venda real ausente.');
if(!worker.includes('Postagem EnvioEcom criada ou em preparação'))fail.push('Trava de postagem EnvioEcom ausente.');
if(!worker.includes('Pagamento ainda ativo; cancele ou aguarde expirar'))fail.push('Trava para pagamento ativo ausente.');
if(!worker.includes('"action_required"')||!worker.includes('"pending_contingency"')||!worker.includes('"authorized"'))fail.push('Trava de estados intermediários do Mercado Pago incompleta.');
if(!worker.includes('Status de pagamento não encerrado ou não reconhecido'))fail.push('Política não está deny-by-default para status desconhecido.');
if(!worker.includes('Status bruto do Mercado Pago ainda não permite exclusão'))fail.push('Status bruto do Mercado Pago não está sendo validado.');
if(worker.includes('["Aguardando pagamento","Processando"].includes(String(row?.status||""))'))fail.push('Política antiga e permissiva de status ainda presente.');
if(!worker.includes('"admin_deleting"'))fail.push('Lock exclusivo durante exclusão administrativa ausente.');
if(!worker.includes('createdAfterLock'))fail.push('Rechecagem de postagem após lock administrativo ausente.');
if(!worker.includes('shipment_locks'))fail.push('Proteção por lock de postagem ausente.');
if(!worker.includes('shipping_id')||!worker.includes('barcode')||!worker.includes('tracking_code'))fail.push('Proteção pelos identificadores de postagem/rastreio incompleta.');
if(!worker.includes('stock_deducted')||!worker.includes('UPDATE inventory SET stock=stock+?'))fail.push('Restauração de estoque da limpeza ausente.');
if(!worker.includes('admin.id')||!worker.includes('admin.email'))fail.push('Limpeza não está limitada à própria conta administrativa.');
if(!admin.includes('vaDeleteOrder'))fail.push('Seleção individual de pedidos de teste ausente.');
if(!admin.includes('APAGAR SELECIONADOS'))fail.push('Ação de limpeza em lote ausente.');
if(!admin.includes('data-delete-one'))fail.push('Ação de limpeza pedido a pedido ausente.');
if(!admin.includes('Digite APAGAR'))fail.push('Confirmação explícita da exclusão ausente.');
if(!admin.includes('CLIENTE REAL'))fail.push('Painel não sinaliza venda real protegida.');
if(!admin.includes('PENDENTE · 24H'))fail.push('Painel não sinaliza validade de 24h dos cadastros pendentes.');
if(!worker.includes('cleanupExpiredPendingCustomers'))fail.push('Limpeza automática de cadastros pendentes expirados ausente.');
if(!worker.includes('cleanupExpiredPendingEmail'))fail.push('Recadastro não limpa pendência expirada do mesmo e-mail.');
if(!worker.includes('Promise.all([reconcileStalePixReservations(env),cleanupExpiredPendingCustomers(env)])'))fail.push('Cron não executa limpeza periódica das pendências.');
if(!worker.includes('NOT EXISTS(SELECT 1 FROM orders o WHERE o.customer_id=customers.id)'))fail.push('Limpeza de pendência não protege pedidos vinculados.');
if(!worker.includes('NOT EXISTS(SELECT 1 FROM guest_orders g WHERE lower(g.email)=lower(customers.email))'))fail.push('Limpeza de pendência não protege pedidos legados pelo e-mail.');
if(!worker.includes('NOT EXISTS(SELECT 1 FROM admin_credentials a WHERE a.customer_id=customers.id)'))fail.push('Limpeza de pendência não protege conta administrativa.');
try{new Function(admin)}catch(e){fail.push('JavaScript admin inválido: '+e.message)}
if(fail.length){console.error('\nADMIN REPROVADO — '+fail.length+' erro(s):\n- '+fail.join('\n- ')+'\n');process.exit(1)}
console.log('ADMIN APROVADO — deny-by-default para pagamentos, action_required protegido, lock anti-corrida do EnvioEcom e exclusões de teste arquivadas.');
